name: Update Index Page

on:
  push:
    branches: 
      - main

jobs:
  update_html_and_readme:
    runs-on: ubuntu-latest
    steps:
      #Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

    #Step 2: Update the index.html
      - name: Update index.html
        run: sed -i '/<\/body>/i <p>Updated by Tea Leader on '"$(date)"'<p>' index.html
